name: Security

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  security:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start application
        run: npm start &

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:3000'
